import store from "@/store";

export default [
    {
        path: "pay",
        name: "AdminPay",
        component: () => import("@/views/zhifu/zhifu"),
        meta: { authLogin: true },
    },

    {
        path: "wxuser",
        name: "AdminwxuserList",
        component: () => import("@/views/wxuser/list"),
        meta: { title: "微信用户列表", authLogin: true },
    },
    {
        path: "wxuseradd",
        name: "AdminwxuserAdd",
        component: () => import("@/views/wxuser/add"),
        meta: { title: "添加微信用户", authLogin: true },
    },
    {
        path: "wxuserupdt",
        name: "AdminwxuserUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/wxuser/updt"),
        meta: { title: "编辑微信用户", authLogin: true },
    },
    {
        path: "admins",
        name: "AdminadminsList",
        component: () => import("@/views/admins/list"),
        meta: { title: "管理员列表", authLogin: true },
    },
    {
        path: "adminsadd",
        name: "AdminadminsAdd",
        component: () => import("@/views/admins/add"),
        meta: { title: "添加管理员", authLogin: true },
    },
    {
        path: "adminsupdt",
        name: "AdminadminsUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/admins/updt"),
        meta: { title: "编辑管理员", authLogin: true },
    },
    {
        path: "adminsupdtself",
        name: "AdminadminsUpdtSelf",
        props: (route) => ({ id: store.state.user.session.id }),
        component: () => import("@/views/admins/updt"),
        meta: { title: "编辑管理员", authLogin: true },
    },
    {
        path: "yonghu",
        name: "AdminyonghuList",
        component: () => import("@/views/yonghu/list"),
        meta: { title: "用户列表", authLogin: true },
    },
    {
        path: "yonghuadd",
        name: "AdminyonghuAdd",
        component: () => import("@/views/yonghu/add"),
        meta: { title: "添加用户", authLogin: true },
    },
    {
        path: "yonghuupdt",
        name: "AdminyonghuUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/yonghu/updt"),
        meta: { title: "编辑用户", authLogin: true },
    },
    {
        path: "yonghuupdtself",
        name: "AdminyonghuUpdtSelf",
        props: (route) => ({ id: store.state.user.session.id }),
        component: () => import("@/views/yonghu/updt"),
        meta: { title: "编辑用户", authLogin: true },
    },
    {
        path: "jingdianxinxi",
        name: "AdminjingdianxinxiList",
        component: () => import("@/views/jingdianxinxi/list"),
        meta: { title: "景点信息列表", authLogin: true },
    },
    {
        path: "jingdianxinxiadd",
        name: "AdminjingdianxinxiAdd",
        component: () => import("@/views/jingdianxinxi/add"),
        meta: { title: "添加景点信息", authLogin: true },
    },
    {
        path: "jingdianxinxiupdt",
        name: "AdminjingdianxinxiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/jingdianxinxi/updt"),
        meta: { title: "编辑景点信息", authLogin: true },
    },
    {
        path: "jingdianxinxidetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminjingdianxinxiDetail",
        component: () => import("@/views/jingdianxinxi/detail"),
        meta: { title: "景点信息详情", authLogin: true },
    },
    {
        path: "diqu",
        name: "AdmindiquList",
        component: () => import("@/views/diqu/list"),
        meta: { title: "地区列表", authLogin: true },
    },
    {
        path: "diquadd",
        name: "AdmindiquAdd",
        component: () => import("@/views/diqu/add"),
        meta: { title: "添加地区", authLogin: true },
    },
    {
        path: "diquupdt",
        name: "AdmindiquUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/diqu/updt"),
        meta: { title: "编辑地区", authLogin: true },
    },
    {
        path: "menpiao",
        name: "AdminmenpiaoList",
        component: () => import("@/views/menpiao/list"),
        meta: { title: "门票列表", authLogin: true },
    },
    {
        path: "menpiaoadd",
        name: "AdminmenpiaoAdd",
        component: () => import("@/views/menpiao/add"),
        meta: { title: "添加门票", authLogin: true },
    },
    {
        path: "menpiaoupdt",
        name: "AdminmenpiaoUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/menpiao/updt"),
        meta: { title: "编辑门票", authLogin: true },
    },
    {
        path: "menpiaodetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminmenpiaoDetail",
        component: () => import("@/views/menpiao/detail"),
        meta: { title: "门票详情", authLogin: true },
    },
    {
        path: "goupiao",
        name: "AdmingoupiaoList",
        component: () => import("@/views/goupiao/list"),
        meta: { title: "购票列表", authLogin: true },
    },
    {
        path: "goupiao_goumairen",
        name: "AdmingoupiaoListgoumairen",
        component: () => import("@/views/goupiao/list-goumairen"),
        meta: { title: "购票列表", authLogin: true },
    },
    {
        path: "goupiaoadd",
        name: "AdmingoupiaoAdd",
        component: () => import("@/views/goupiao/add"),
        meta: { title: "添加购票", authLogin: true },
    },
    {
        path: "goupiaoupdt",
        name: "AdmingoupiaoUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/goupiao/updt"),
        meta: { title: "编辑购票", authLogin: true },
    },
    {
        path: "goupiaodetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdmingoupiaoDetail",
        component: () => import("@/views/goupiao/detail"),
        meta: { title: "购票详情", authLogin: true },
    },
    {
        path: "meishixinxi",
        name: "AdminmeishixinxiList",
        component: () => import("@/views/meishixinxi/list"),
        meta: { title: "美食信息列表", authLogin: true },
    },
    {
        path: "meishixinxiadd",
        name: "AdminmeishixinxiAdd",
        component: () => import("@/views/meishixinxi/add"),
        meta: { title: "添加美食信息", authLogin: true },
    },
    {
        path: "meishixinxiupdt",
        name: "AdminmeishixinxiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/meishixinxi/updt"),
        meta: { title: "编辑美食信息", authLogin: true },
    },
    {
        path: "meishixinxidetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminmeishixinxiDetail",
        component: () => import("@/views/meishixinxi/detail"),
        meta: { title: "美食信息详情", authLogin: true },
    },
    {
        path: "meishifenlei",
        name: "AdminmeishifenleiList",
        component: () => import("@/views/meishifenlei/list"),
        meta: { title: "美食分类列表", authLogin: true },
    },
    {
        path: "meishifenleiadd",
        name: "AdminmeishifenleiAdd",
        component: () => import("@/views/meishifenlei/add"),
        meta: { title: "添加美食分类", authLogin: true },
    },
    {
        path: "meishifenleiupdt",
        name: "AdminmeishifenleiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/meishifenlei/updt"),
        meta: { title: "编辑美食分类", authLogin: true },
    },
    {
        path: "lunbotu",
        name: "AdminlunbotuList",
        component: () => import("@/views/lunbotu/list"),
        meta: { title: "轮播图列表", authLogin: true },
    },
    {
        path: "lunbotuadd",
        name: "AdminlunbotuAdd",
        component: () => import("@/views/lunbotu/add"),
        meta: { title: "添加轮播图", authLogin: true },
    },
    {
        path: "lunbotuupdt",
        name: "AdminlunbotuUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/lunbotu/updt"),
        meta: { title: "编辑轮播图", authLogin: true },
    },
    {
        path: "pinglun",
        name: "AdminpinglunList",
        component: () => import("@/views/pinglun/list"),
        meta: { title: "评论列表", authLogin: true },
    },
    {
        path: "pinglun_pinglunren",
        name: "AdminpinglunListpinglunren",
        component: () => import("@/views/pinglun/list-pinglunren"),
        meta: { title: "评论列表", authLogin: true },
    },
    {
        path: "pinglunupdt",
        name: "AdminpinglunUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/pinglun/updt"),
        meta: { title: "编辑评论", authLogin: true },
    },
];
